site_name: MCF Pipe

nav:
  - Home: index.md
  - Workflows: workflows.md
  - Architecture: architecture.md
  - CICD: cicd.md
  - Data Model: data_model.md
  - Enhancements: enhancements.md
  - Releases:
      - 0.1.0: releases/010_cloud_infra.md

theme:
  name: material
  palette:
    scheme: default
    primary: custom
    accent: custom

extra_css:
  - stylesheets/overrides.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format