name: Config and Network Infra

on:
  workflow_dispatch: 
  push:
    paths:
      - '.github/workflows/setup.yml'
      - 'aws/cloudformation/network_stack.yaml'
      - 'setup/export_network_outputs.sh'
      - 'setup/config.env'

jobs:
  validate-docker-image:
    name: Run Docker Image Build
    runs-on: ubuntu-latest

    env:
      STACK_NAME: mcf-network
      STACK_TEMPLATE: aws/cloudformation/networking_stack.yaml
      NETWORK_CONFIG_JSON: network_config.json
      NETWORK_CONFIG_S3_PATH: aws/network
      NETWORK_CONFIG_EXPORT_SCRIPT: setup/export_network_config.sh

    steps:
    - name: Init Run Status
      id: initialize_run_status
      run: echo "SETUP_SUCCESS=true" >> $GITHUB_ENV

    - name: Checkout repository
      id: repo_checkout
      uses: actions/checkout@v3

    - name: Load environment config
      id: env_var_set
      run: cat setup/config.env >> $GITHUB_ENV

    - name: Configure AWS credentials
      id: aws_config
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Ensure S3 bucket exists
      id: s3_bucket_create
      run: |
                if ! aws s3api head-bucket --bucket $S3_BUCKET 2>/dev/null; then
                echo "Creating S3 bucket: $S3_BUCKET"
                  aws s3 mb s3://$S3_BUCKET --region $AWS_REGION
                else
                  echo "Bucket $S3_BUCKET already exists"
                fi

    - name: Deploy Network CloudFormation Stack
      id: deploy_network_stack
      run: |
        aws cloudformation deploy \
        --template-file $STACK_TEMPLATE \
        --stack-name $STACK_NAME \
        --capabilities CAPABILITY_NAMED_IAM \
        --parameter-overrides \
            EnvStage=prod \
            ConfigBucket=$S3_BUCKET \
        --tags \
            role=$ROLE \
            project=$PROJECT_NAME

    - name: Export network outputs to S3
      id: network_outputs
      run: |
        chmod +x ./$NETWORK_CONFIG_EXPORT_SCRIPT
        ./$NETWORK_CONFIG_EXPORT_SCRIPT "${{ env.STACK_NAME }}" "${{ env.AWS_REGION }}" "${{ env.S3_BUCKET }}" "${{ env.NETWORK_CONFIG_S3_PATH }}/${{ env.NETWORK_CONFIG_JSON }}"

    - name: Fail workflow if build failed
      if: env.SETUP_SUCCESS == 'false'
      run: |
        echo "Setup failed"
        exit 1